/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import JavaClass.Club;
import JavaClass.Sport;
import JavaClass.SportBallon;
import JavaClass.SportRelais;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex
 */
public class frmPrincipal extends javax.swing.JFrame {

    DefaultTableModel dtmClub;
    DefaultTableModel dtmSport;
    
    ArrayList<Club> mesClubs;
    
    Vector v;
    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblClub = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSports = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblClub.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nom", "Nb Points"
            }
        ));
        tblClub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClubMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClub);

        jLabel1.setText("Liste des clubs");

        tblSports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Nb Joueur", "Description", "Largeur terrain", "Largeur terrain", "Distance"
            }
        ));
        jScrollPane2.setViewportView(tblSports);

        jLabel2.setText("Liste des Sports du club sélectionné");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 257, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        dtmClub = (DefaultTableModel) tblClub.getModel();
        dtmSport = (DefaultTableModel) tblSports.getModel();
        
        Club c1 = new Club(1, "Dijon", 63);
        Club c2 = new Club(2, "PSG", 63);
        Club c3 = new Club(3, "Nante", 63);
        
        SportBallon sb = new SportBallon("Basketball", 5, 35, 45);
        c1.AjouterSport(sb);
        
        Sport s1 = new Sport("Javelot", 1);
        Sport s2 = new Sport("Judo", 1);
        SportBallon sb1 = new SportBallon("Football", 11, 68, 105);
        SportBallon sb2 = new SportBallon("Handball", 7, 35, 65);
        SportRelais sr1 = new SportRelais("4 * 100", 400, 4);
        
        c2.AjouterSport(s1);
        c2.AjouterSport(s2);
        c2.AjouterSport(sb1);
        c2.AjouterSport(sb2);
        c2.AjouterSport(sr1);
        
        Sport s3 = new Sport("Cyclisme", 1);
        SportBallon sb3 = new SportBallon("Football", 11, 68, 105);
        SportBallon sb4 = new SportBallon("Rugby", 11, 65, 115);
        SportRelais sr2 = new SportRelais("100 mètres", 100, 1);
        
        c3.AjouterSport(s3);
        c3.AjouterSport(sb3);
        c3.AjouterSport(sb4);
        c3.AjouterSport(sr2);
        
        mesClubs = new ArrayList();
        mesClubs.add(c1);
        mesClubs.add(c2);
        mesClubs.add(c3);
        
        Collections.sort(mesClubs);
        
        for(Club c : mesClubs)
        {
            v = new Vector();
            v.add(c.getIdClub());
            v.add(c.getNomClub());
            v.add(c.getNbPoints());
            dtmClub.addRow(v);
        }
        tblClub.setModel(dtmClub);
        
    }//GEN-LAST:event_formWindowOpened

    private void tblClubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClubMouseClicked
        // TODO add your handling code here:
        while(tblSports.getRowCount() != 0)
        {
            dtmSport.removeRow(0);
        }
        String nomClubSelected = tblClub.getValueAt(tblClub.getSelectedRow(),1).toString();
        for(Club c : mesClubs)
        {
            if (nomClubSelected.equals(c.getNomClub()))
            {
                for(Sport s : c.getLesSports())
                {
                    v = new Vector();
                    v.add(s.GetNomSport());
                    v.add(s.GetNbJoueur());
                    v.add(s.GetDescription());
                    if(s instanceof SportBallon)
                    {
                        v.add(((SportBallon)s).GetLargeur());
                        v.add(((SportBallon)s).GetLongueur());
                        
                    }
                    if (s instanceof SportRelais)
                    {
                        v.add(null);
                        v.add(null);
                        v.add(((SportRelais)s).getDistance());
                    }
                    dtmSport.addRow(v);
                }
                tblSports.setModel(dtmSport);
            }
            
            
        }
    }//GEN-LAST:event_tblClubMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblClub;
    private javax.swing.JTable tblSports;
    // End of variables declaration//GEN-END:variables
}
